name: Louis App Tests

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - develop
      - louis-test
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  Test:
    timeout-minutes: 40
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kong'

      - name: Install packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KONG_PACKAGES_READ_TOKEN }}
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Build app for Louis tests
        run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      - name: Run Louis Test project
        run: npm run test:build -w packages/insomnia-smoke-test -- --project="Louis Test"

      - name: Run Allure Action
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: ./
        with:
          report-directory: "./out/allure-report"
          remote-href: "https://allure-framework.github.io/allure-action/${{ steps.path.outputs.subdir }}"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/allure-report
          publish_branch: gh-pages
          destination_dir: ${{ steps.path.outputs.subdir }}
          keep_files: true
