name: Louis App Tests

on:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - develop
      - louis-test
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  Test:
    timeout-minutes: 40
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kong'

      # - name: Configure npm auth for GitHub Packages
      #   run: |
      #     echo "@kong:registry=https://npm.pkg.github.com" >> ~/.npmrc
      #     echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
      #     echo "always-auth=true" >> ~/.npmrc
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps without lifecycle scripts
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Build app for Louis tests
        run: NODE_OPTIONS='--max_old_space_size=6144' npm run app-build

      - name: Run Louis Test project
        run: npm run test:build -w packages/insomnia-smoke-test -- --project="Louis Test"
        
      - name: Upload smoke test
        uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          if-no-files-found: ignore
          name: ubuntu-smoke-test-traces-${{ github.run_number }}
          path: packages/insomnia-smoke-test/traces
